name: Integrate ComicGeek Application

on:
  pull_request: 
    branches:
      - main
    paths: 
      - 'src/**'
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.x.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-restore --verbosity normal --logger trx
      - uses: bibipkins/dotnet-test-reporter@v1.4.0
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            comment-title: 'Test Results'
            results-path: ./**/*.trx
            coverage-path: ./**/coverage.cobertura.xml
            coverage-type: cobertura
            coverage-threshold: 80